/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasBoard: typeof import('./src/components/CanvasBoard.vue')['default']
    ChatView: typeof import('./src/components/ChatView.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    ControlCenter: typeof import('./src/components/ControlCenter.vue')['default']
    CustomTemplateCreator: typeof import('./src/components/CustomTemplateCreator.vue')['default']
    DeviceDialog: typeof import('./src/components/DeviceDialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    Header: typeof import('./src/components/Header.vue')['default']
    LogoutConfirm: typeof import('./src/components/LogoutConfirm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleBuilderDialog: typeof import('./src/components/RuleBuilderDialog.vue')['default']
    SimulationTimeline: typeof import('./src/components/SimulationTimeline.vue')['default']
    SystemInspector: typeof import('./src/components/SystemInspector.vue')['default']
    TraceVisualization: typeof import('./src/components/TraceVisualization.vue')['default']
  }
}
