/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountDeleteDialog: typeof import('./src/components/AccountDeleteDialog.vue')['default']
    AppErrorBoundary: typeof import('./src/components/AppErrorBoundary.vue')['default']
    CanvasBoard: typeof import('./src/components/CanvasBoard.vue')['default']
    ChatMarkdown: typeof import('./src/components/ChatMarkdown.vue')['default']
    ChatView: typeof import('./src/components/ChatView.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    ControlCenter: typeof import('./src/components/ControlCenter.vue')['default']
    DeviceDialog: typeof import('./src/components/DeviceDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FixResultDialog: typeof import('./src/components/FixResultDialog.vue')['default']
    FuzzingPanel: typeof import('./src/components/FuzzingPanel.vue')['default']
    FuzzingResultDialog: typeof import('./src/components/FuzzingResultDialog.vue')['default']
    InfoTooltip: typeof import('./src/components/common/InfoTooltip.vue')['default']
    LanguageToggle: typeof import('./src/components/common/LanguageToggle.vue')['default']
    LogoutConfirm: typeof import('./src/components/LogoutConfirm.vue')['default']
    LogoutConfirmDialog: typeof import('./src/components/LogoutConfirmDialog.vue')['default']
    PlaybackChangePopover: typeof import('./src/components/PlaybackChangePopover.vue')['default']
    PublicHeader: typeof import('./src/components/common/PublicHeader.vue')['default']
    RecommendationProgressStatus: typeof import('./src/components/RecommendationProgressStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleBuilderDialog: typeof import('./src/components/RuleBuilderDialog.vue')['default']
    ScenarioObjectiveIssues: typeof import('./src/components/ScenarioObjectiveIssues.vue')['default']
    SimulationTimeline: typeof import('./src/components/SimulationTimeline.vue')['default']
    SystemInspector: typeof import('./src/components/SystemInspector.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    TraceHistoryPanel: typeof import('./src/components/TraceHistoryPanel.vue')['default']
  }
}
