package cn.edu.nju.Iot_Verify.po;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * One reversible board edit, recorded in the same transaction as the edit itself.
 *
 * <p>The journal is append-only: undo and redo move {@link #undone} rather than deleting rows,
 * so a redo never has to reconstruct an entry that was thrown away. Each entry stores the
 * payload needed to reach the <em>other</em> state, which for this journal is always a complete
 * snapshot of the single affected rule or specification — small, self-contained, and immune to
 * later edits of neighbouring records.
 *
 * <p>Ordering is by {@link #sequence}, a per-user counter, so concurrent sessions of the same
 * account cannot interleave into an ambiguous order.
 */
@Entity
// The unique constraint is the fence behind BoardEditJournal's read-max-then-add-one allocation: a
// lost race must fail with a duplicate key and retry, not write two entries sharing an ordinal. It is
// declared here so a schema generated by ddl-auto has it too — BoardEditJournalSequenceUniqueness
// only adds it to databases that already exist. The plain index is redundant with the unique one's
// leading columns, so it is gone.
@Table(name = "board_edit_journal", uniqueConstraints = {
        @UniqueConstraint(name = "uk_board_edit_journal_user_sequence",
                columnNames = {"user_id", "sequence"})
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class BoardEditJournalPo {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    /** Monotonic per user. Defines undo/redo order independently of clock skew or row ids. */
    @Column(name = "sequence", nullable = false)
    private Long sequence;

    @Enumerated(EnumType.STRING)
    @Column(name = "entity_type", nullable = false, length = 32)
    private BoardEditEntityType entityType;

    @Enumerated(EnumType.STRING)
    @Column(name = "operation", nullable = false, length = 32)
    private BoardEditOperation operation;

    /** Business key of the affected record: the rule id or the specification id. */
    @Column(name = "entity_key", nullable = false, length = 191)
    private String entityKey;

    /**
     * The record as it was before the edit, as canonical JSON. Absent for CREATE, whose inverse
     * is a delete.
     */
    // TEXT rather than JSON: the value is already-serialized JSON held as a String, and a
    // native JSON column re-encodes it as a JSON string literal on some drivers.
    @Column(name = "before_json", columnDefinition = "TEXT")
    private String beforeJson;

    /**
     * The record as it was after the edit. Absent for DELETE, whose inverse is a re-create.
     * Used to detect that something else changed the record since this entry was written.
     */
    @Column(name = "after_json", columnDefinition = "TEXT")
    private String afterJson;

    /**
     * The deleted rule's `execution_order` at the moment of the edit, so undo can restore its
     * position and not just its content.
     *
     * <p>Execution order is user-controlled model semantics (lower rules win per target mode when
     * guards overlap), and {@code RuleDto} deliberately carries no position — it is a client-facing
     * contract that distrusts client-supplied ordering. Null for every entry that is not a rule
     * deletion.
     */
    @Column(name = "entity_order")
    private Integer entityOrder;

    /** False while this edit is in effect, true once undone and available to redo. */
    @Column(name = "undone", nullable = false)
    private boolean undone;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}
