package cn.edu.nju.Iot_Verify.dto.model;

/** Stable reason codes for user-facing localization of model-generation omissions. */
public enum ModelGenerationIssueReasonCode {
    RULE_NO_TRIGGER_CONDITIONS,
    RULE_NULL_TRIGGER_CONDITION,
    RULE_UNRESOLVABLE_TRIGGER_CONDITION,
    RULE_NO_RESOLVABLE_TRIGGER_CONDITIONS,
    RULE_PROPERTY_PROPAGATION_UNAVAILABLE,
    SPEC_NO_CHECKABLE_CONDITIONS,
    SPEC_PRIVACY_MODELING_DISABLED,
    SPEC_UNSUPPORTED_RELATION,
    SPEC_AMBIGUOUS_STATE,
    SPEC_UNDECLARED_SECURITY_PROPERTY,
    SPEC_UNKNOWN_DEVICE,
    SPEC_TEMPLATE_SHAPE_MISMATCH,
    SPEC_INVALID_VALUE,
    SPEC_UNSUPPORTED_CONDITION,
    UNCLASSIFIED_GENERATION_ISSUE
}
